spring:
  datasource:
    url: jdbc:mysql://come-on-toeic.cv6sugwm4m8j.ap-northeast-2.rds.amazonaws.com:3306/come-on-toeic?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret:
    key: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M